ChoreTracker/Controllers/TaskController.cs
using ChoreTracker.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Web.Mvc;

namespace ChoreTracker.Controllers
{
    public class TaskController : Controller
    {
        private readonly ITaskRepository _taskRepository;
        protected ApplicationDbContext ApplicationDbContext { get; set; }
        protected UserManager<ApplicationUser> UserManager { get; set; }
        public TaskController(ITaskRepository taskRepository)
        {
            this.ApplicationDbContext = new ApplicationDbContext();
            this.UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.ApplicationDbContext));
            _taskRepository = taskRepository;
        }

        public ActionResult List()
        {
            return View("TaskView", _taskRepository.GetAllTasks);
        }

        private ActionResult Edit(int id)
        {
            return View();
        }

        public ActionResult Claim(int id)
        {
            var user = UserManager.FindById(User.Identity.GetUserId());
            



            return View("TaskView", _taskRepository.GetAllTasks);
        }
    }
}

ChoreTracker/Views/Task/List.cshtml
@model IEnumerable<FromScratch.Models.TaskModel>


    @foreach (var taskModel in Model)
    {
        <div>
            <h2>@taskModel.Id</h2>
            <h3>@taskModel.Name</h3>
            <h4>@taskModel.Description</h4>
        </div>
    }

ChoreTracker/Views/Task/TaskView.cshtml
@model IEnumerable<ChoreTracker.Models.TaskModel>

@{
    ViewData["Title"] = "TaskView";
}

<h2>TaskView</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="thumbnail">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Value)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DueDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Value)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DueDate)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Task", new {  id=item.Id  }) |
                    @Html.ActionLink("Claim", "Claim", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>

</table>