ChoreTracker/Controllers/CompletedTasksController.cs
using ChoreTracker.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web.Mvc;

namespace ChoreTracker.Controllers
{
	public class CompletedTasksController : Controller
    {
		private DatabaseContext _dbContext = new DatabaseContext();

		// GET: CompletedTasks
		public ActionResult Index()
        {
			var model = _dbContext.Tasks.Where(x => x.Status == Enums.ChoreStatus.Complete);

			return View(model);
		}

		public ActionResult Cancel(int? id)
		{
			if (id != null)
			{
				var taskModel = _dbContext.Tasks.FirstOrDefault(x => x.Id == id);
				taskModel.Status = Enums.ChoreStatus.InProgress;
				

				_dbContext.Tasks.AddOrUpdate(taskModel);
				_dbContext.SaveChanges();
			}

			return RedirectToAction("Index");
		}


		public ActionResult Complete(int? id)
		{
			if (id != null)
			{
				var userId = User.Identity.GetUserId();
				var user = _dbContext.Users.FirstOrDefault(x => x.UserGuid.Equals(userId));

				var taskModel = _dbContext.Tasks.FirstOrDefault(x => x.Id == id);

				if (taskModel != null && user != null)
				{
					//this task should probably be deleted here
					taskModel.Status = Enums.ChoreStatus.New;
					taskModel.AssignedAccountId = string.Empty;

					user.Bank += taskModel.Value;
					_dbContext.Users.AddOrUpdate(user);
					_dbContext.Tasks.AddOrUpdate(taskModel);
					_dbContext.SaveChanges();
				}
			}
			return RedirectToAction("Index");
		}

	}
}

ChoreTracker/Controllers/MyTasksController.cs
using ChoreTracker.Models;
using Microsoft.AspNet.Identity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web.Mvc;

namespace ChoreTracker.Controllers
{
	//should be renamed to something like MyTasksController??
	public class MyTasksController : Controller
    {
        private DatabaseContext _dbContext = new DatabaseContext();

        // GET: AccountView
        public ActionResult Index()
        {
            string userId = User.Identity.GetUserId();

            var model = _dbContext.Tasks.Where(x => x.AssignedAccountId.Equals(userId) && (x.Status == Enums.ChoreStatus.New || x.Status == Enums.ChoreStatus.InProgress)).ToList<TaskModel>();

            return View("MyTasksView", model);
        }

		public ActionResult Start(int id)
		{
			var taskModel = _dbContext.Tasks.FirstOrDefault(x => x.Id == id);

			if (taskModel != null)
			{
				taskModel.Status = Enums.ChoreStatus.InProgress;
				_dbContext.Tasks.AddOrUpdate(taskModel);
				_dbContext.SaveChanges();
			}

			return RedirectToAction("Index");
		}


		public ActionResult Cancel(int id)
        {
            var taskModel = _dbContext.Tasks.FirstOrDefault(x => x.Id == id);

            if (taskModel != null)
            {
				taskModel.Status = Enums.ChoreStatus.New;
                taskModel.AssignedAccountId = string.Empty;
                _dbContext.Tasks.AddOrUpdate(taskModel);
                _dbContext.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public ActionResult Complete(int id)
        {
			var taskModel = _dbContext.Tasks.FirstOrDefault(x => x.Id == id);

            if (taskModel != null)
            {
                taskModel.Status = Enums.ChoreStatus.Complete;
                _dbContext.Tasks.AddOrUpdate(taskModel);
                _dbContext.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

ChoreTracker/Controllers/PrizePurchasesController.cs
using ChoreTracker.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChoreTracker.Controllers
{
    public class PrizePurchasesController : Controller
    {
		DatabaseContext _dbContext = new DatabaseContext();

		// GET: api/Prize/5
		public ActionResult Index()
		{
			//only display prizes that have been purchased
			//The other prizes are displayed on the Prize page
			var model = _dbContext.Prizes.Where(x => !String.IsNullOrEmpty(x.OwnerUserGuid));

			return View("Index", model);
		}

		[Authorize(Roles = "admin")]
		public ActionResult Complete(int id)
		{
			var model = _dbContext.Prizes.FirstOrDefault(x => x.Id == id);

			if (model != null)
			{
				//delete from database
				_dbContext.Prizes.Remove(model);
				_dbContext.SaveChanges();
			}

			return RedirectToAction("Index");
		}		
	}
}

ChoreTracker/Views/Shared/_Layout.cshtml
@using ChoreTracker.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @{ 
        var _dbContext = new DatabaseContext();
        int _purchaseCount = _dbContext.Prizes.Where(x => !String.IsNullOrEmpty(x.OwnerUserGuid)).Count();
        int _completedTaskCount = _dbContext.Tasks.Where(x => x.Status == Enums.ChoreStatus.Complete).Count();

    }

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("admin") || User.IsInRole("user"))
                            {
                                <li>@Html.ActionLink("My Tasks", "Index", "MyTasks")</li>
                                if (_completedTaskCount > 0)
                                {
                                    <li>@Html.ActionLink("Completed", "Index", "CompletedTasks")</li>
                                }
                            }
                        }
                        <li>@Html.ActionLink("Prizes", "Prize", "Prize")</li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if ((User.IsInRole("admin") || User.IsInRole("user")) && _purchaseCount > 0)
                            {
                                <li>@Html.ActionLink("Purchases", "Index", "PrizePurchases")</li>
                            }
                        }
                        <li>@Html.ActionLink("Rules", "Contact", "Home")</li>
                    </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>